//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_es_ES {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_es_ES() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Portfolio.Resources.SharedResource_es_ES", typeof(SharedResource_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string bienvenido {
            get {
                return ResourceManager.GetString("bienvenido", resourceCulture);
            }
        }
        
        internal static string descargaCv {
            get {
                return ResourceManager.GetString("descargaCv", resourceCulture);
            }
        }
        
        internal static string seleccionIdioma {
            get {
                return ResourceManager.GetString("seleccionIdioma", resourceCulture);
            }
        }
        
        internal static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        internal static string tituloBienvenida {
            get {
                return ResourceManager.GetString("tituloBienvenida", resourceCulture);
            }
        }
        
        internal static string tituloPrincipal {
            get {
                return ResourceManager.GetString("tituloPrincipal", resourceCulture);
            }
        }
        
        internal static string trabajoReciente {
            get {
                return ResourceManager.GetString("trabajoReciente", resourceCulture);
            }
        }
        
        internal static string visitar {
            get {
                return ResourceManager.GetString("visitar", resourceCulture);
            }
        }
        
        internal static string proyectos {
            get {
                return ResourceManager.GetString("proyectos", resourceCulture);
            }
        }
        
        internal static string derechosReservados {
            get {
                return ResourceManager.GetString("derechosReservados", resourceCulture);
            }
        }
        
        internal static string misProyectos {
            get {
                return ResourceManager.GetString("misProyectos", resourceCulture);
            }
        }
        
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        internal static string todosLosProyectos {
            get {
                return ResourceManager.GetString("todosLosProyectos", resourceCulture);
            }
        }
        
        internal static string hablamos_ {
            get {
                return ResourceManager.GetString("hablamos?", resourceCulture);
            }
        }
        
        internal static string completaElFormulario {
            get {
                return ResourceManager.GetString("completaElFormulario", resourceCulture);
            }
        }
        
        internal static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        internal static string mensaje {
            get {
                return ResourceManager.GetString("mensaje", resourceCulture);
            }
        }
        
        internal static string graciasPorMensaje {
            get {
                return ResourceManager.GetString("graciasPorMensaje", resourceCulture);
            }
        }
        
        internal static string mePondreEnContacto {
            get {
                return ResourceManager.GetString("mePondreEnContacto", resourceCulture);
            }
        }
        
        internal static string volverInicio {
            get {
                return ResourceManager.GetString("volverInicio", resourceCulture);
            }
        }
        
        internal static string subtituloBienvenida {
            get {
                return ResourceManager.GetString("subtituloBienvenida", resourceCulture);
            }
        }
        
        internal static string subtituloBack {
            get {
                return ResourceManager.GetString("subtituloBack", resourceCulture);
            }
        }
        
        internal static string subtituloFront {
            get {
                return ResourceManager.GetString("subtituloFront", resourceCulture);
            }
        }
        
        internal static string experiencia {
            get {
                return ResourceManager.GetString("experiencia", resourceCulture);
            }
        }
        
        internal static string algunosTrabajos {
            get {
                return ResourceManager.GetString("algunosTrabajos", resourceCulture);
            }
        }
        
        internal static string escribiMensaje {
            get {
                return ResourceManager.GetString("escribiMensaje", resourceCulture);
            }
        }
        
        internal static string tuNombre {
            get {
                return ResourceManager.GetString("tuNombre", resourceCulture);
            }
        }
    }
}
